### ISSUE TITLE
readme example does not work if you fail to do a simple copy+paste

### ISSUE THREAD

**Issue by qwertzui11** [atilaneves/tardy#13]
Hi there!

I just wasted half an hour, because I copy+pasted the README example function by function. However I forgot to copy the `xform` function. :smile: 
It seems like tardy defines the function `xform` which leads to errors, which are difficult to find for a newbie, because the compile error looks like this:

```
|| source/tardy_fun.d(34,21): Error: function `tardy.xform(Polymorphic!(ITransformer, GC) t)` is not callable using argument types `(Polymorphic!(ITransformer, GC))`
|| source/tardy_fun.d(34,21):        cannot pass argument `((Polymorphic!(ITransformer, GC) __slPolymo1543 = Polymorphic(null, null);) , __slPolymo1543).this(Adder(2))` of type `tardy.poly.Polymorphic!(ITransformer, GC)` to parameter `tardy.poly.Polymorphic!(ITransformer, GC) t`
|| source/tardy_fun.d(35,21): Error: function `tardy.xform(Polymorphic!(ITransformer, GC) t)` is not callable using argument types `(Polymorphic!(ITransformer, GC))`
|| source/tardy_fun.d(35,21):        cannot pass argument `((Polymorphic!(ITransformer, GC) __slPolymo1544 = Polymorphic(null, null);) , __slPolymo1544).this(Adder(3))` of type `tardy.poly.Polymorphic!(ITransformer, GC)` to parameter `tardy.poly.Polymorphic!(ITransformer, GC) t`
|| source/tardy_fun.d(38,21): Error: function `tardy.xform(Polymorphic!(ITransformer, GC) t)` is not callable using argument types `(Polymorphic!(ITransformer, GC))`
|| source/tardy_fun.d(38,21):        cannot pass argument `transformer` of type `tardy.poly.Polymorphic!(ITransformer, GC)` to parameter `tardy.poly.Polymorphic!(ITransformer, GC) t`
```

`Polymorphic!(ITransformer, GC) t)` != `(Polymorphic!(ITransformer, GC)` wtf. I only saw the different packages when it was too late.

May I suggest you change the example in one of the following ways:

- import only whats needed
```d
import tardy : Polymorphic;
```
- rename `xform` to something else.
- don't export `xform`. I guess https://github.com/atilaneves/tardy/blob/d5f1102a6a791e77e0a27ee1a7920166fba8fcc8/source/tardy/package.d should be more private.

Thanks for your time! Awesome project!

**Comment by atilaneves** [comment]
Ugh, I hate `version(unittest)`.

**Comment by qwertzui11** [comment]
May you point me to link how to do tests correctly - the non unittest version? :laughing:

**Comment by atilaneves** [comment]
You didn't do anything wrong - I did, by using `version(unittest)` even though I know it's broken and keep telling other people not to until we fix it.

**Comment by qwertzui11** [comment]
thx for the info and the fix!
